
# Contact
title: Michael Braverman
author: Michael Braverman
email: bravm321@newschool.edu

# Social Media
twitter_username: mixania
github_username:  mbrav
vimeo_username: mbrav
instagram_username: mbrav_
flickr_username: mixania
soundcloud_username: mixania

description: A blog and collection of essays and writings that explore design, knowledge, and aesthetics.
baseurl: ""
url: "http://www.mbrav.com"

# Custom names for different kinds of collections
collections:
  posts:
    output: true
    permalink: post/:title
  projects:
    output: true
    permalink: project/:title
  journals:
    output: true
    permalink: journals/:year/:month/:day

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# for jekyll-seo-tag
twitter:
  username: mixania

# For Atom editor
atom:
  postDirs:
    - _projects
    - _journals
