# Setup
title: Michael Braverman
author: Michael Braverman
tagline: portfolio / personal site
email: mbrav@protonmail.com
description: "Michael Braverman's portfolio site"
baseurl: ""
url: "http://www.mbrav.com"

# Social Media
twitter_username: absurdcomrade
github_username:  mbrav
vimeo_username: mbrav
instagram_username: absurdcomrade
flickr_username: mixania
soundcloud_username: mixania
# medium_username: mbrav
# tumblr_username: bravm

# Custom names for different categories
defaults:
  # blogs
  - scope:
      path: "_posts/blog"
      type: posts
    values:
      categories: blog
      permalink: blog/:year/:month/:title
  # Posts
  - scope:
      path: "_posts/writing"
      type: posts
    values:
      categories: writing
      permalink: post/:title
  # Work
  - scope:
      path: "_posts/work"
      type: posts
    values:
      categories: work
      permalink: work/:title
  # Reading Notes
  - scope:
      path: "_posts/annotation"
      type: posts
    values:
      categories: annotation
      permalink: annotation/:title
  # Thesis
  - scope:
      path: "_posts/thesis"
      type: posts
    values:
      categories: thesis
      permalink: thesis/:title

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
  - LISCENSE.md
  - Gemfile
  - Gemfile.lock

# Custom gems
plugins: [jekyll-seo-tag, jekyll-feed, jekyll-sitemap, jekyll-github-metadata]

# For jekyll-seo-tag
twitter:
  username: mixania

# for comments
disqus:
  shortname: mbrav

# For the AI-illuminati-conspiracy-data-tracking boys
google_analytics: UA-90389714-1

# For Atom Jekyll plugin
atom:
  postDirs:
    - _posts/work
    - _posts/blog
    - _posts/writing
    - _posts/annotation
    - _posts/thesis
