
title: Michael Braverman
author: Michael Braverman
email: bravm321@newschool.edu
description: > # this means to ignore newlines until "baseurl:"
  A blog and collection of essays and writings that explore design, knowledge, and aesthetics.
# baseurl: "/studies" # the subpath of your site, e.g. /blog
url: "http://www.mbrav.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mixania
github_username:  mbrav

permalink: /:title.html

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
