# Setup
title: Michael Braverman
author: Michael Braverman
tagline: portfolio / personal site
email: bravm321@newschool.edu
description: "Michael Braverman's portfolio site"
baseurl: ""
url: "http://www.mbrav.com"

# Social Media
twitter_username: mixania
github_username:  mbrav
vimeo_username: mbrav
instagram_username: mbrav_
flickr_username: mixania
soundcloud_username: mixania
# medium_username: mbrav
tumblr_username: bravm

# Custom names for different categories
defaults:
  # Journals
  - scope:
      path: "_posts/journal"
      type: posts
    values:
      categories: journal
      permalink: journal/:year/:month/:day
  # Posts
  - scope:
      path: "_posts/writing"
      type: posts
    values:
      categories: writing
      permalink: post/:title
  # Project
  - scope:
      path: "_posts/project"
      type: posts
    values:
      categories: project
      permalink: project/:title

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
  - LISCENSE.md
  - Gemfile
  - Gemfile.lock

# Custom gems
gems: [jekyll-seo-tag, jekyll-feed, jekyll-sitemap, jekyll-github-metadata]

# For jekyll-seo-tag
twitter:
  username: mixania

# for comments
disqus:
  shortname: mbrav

# For the AI-illuminati-conspiracy-data-tracking boys
google_analytics: UA-90389714-1

# For Atom Jekyll plugin
atom:
  postDirs:
    - _posts/project
    - _posts/journal
    - _posts/writing
